### PR TITLE
Update string.go

### PR DESCRIPTION
**Pull request by liujundezhanghao**
more reasonable

### CODE REVIEW

**Comment by ccoVeille** [comment]
Could you please add test for this use case?

It's unclear what you are fixing, and someone could open a PR and make the opposite changes

**Comment by liujundezhanghao** [comment]
Because if the offsets are equal in size, the following logic is meaningless.

**Comment by liujundezhanghao** [comment]
Thanks, I added it

**Comment by ccoVeille** [comment]
Thanks for doing the changes. Let's wait for maintainers feedback now

**Comment by samber** [comment]
👌 Good point

**Pull request merged**
