### PR TITLE
Adding FindOrElse and tests

### PR DESCRIPTION
**Pull request by muety**
Addresses issues #52, #54 and #59

### CODE REVIEW

**Comment by metalrex100** [comment]
@muety according to [yangchnet](https://github.com/yangchnet) comment in #59 there is also typo in comment to `UniqBy` function: https://github.com/samber/lo/blob/master/slice.go#L89.
Can you include fix for it in this PR?

**Comment by muety** [comment]
Sure, done!

**Comment by muety** [comment]
Any news here?

**Comment by metalrex100** [comment]
@muety seems like only @samber can approve and merge PR's, but he does not respond often here..

**Comment by samber** [comment]
Hi there, and sorry for the late reply.

@muety could you please remove `All` and `Any`? We need to discuss it in #54 and the #67 looks more complete.

I will merge this soon after ;)

**Comment by muety** [comment]
Sure, done! I rebased onto latest master.

**Pull request merged**
