### PR TITLE
Add slice Splice an element or multiple elements at index i.

### PR DESCRIPTION
**Pull request by wenlingang**
Inserts an element or multiple elements at index i.

### CODE REVIEW

**Review by 1800alex — COMMENTED** [review]
This code looks good to me, anything preventing this from being merged? Would like to make use of it

**Comment by 1800alex** [comment]
On second glance, something seems off

```
package slices

import (
	"testing"
)

// Insert inserts an element at index i.
// Play: https://go.dev/play/p/Eu3pk6_ODVQ
func Insert[T any](collection []T, i int, element T) []T {
	result := make([]T, len(collection)+1)
	copy(result, collection[:i])
	result[i] = element
	copy(result[i+1:], collection[i:])

	return result
}

// Insert inserts an element at index i.
func Insert2[T any](collection []T, i int, element T) []T {
	return append(collection[:i], append([]T{element}, collection[i:]...)...)
}

func BenchmarkInsertSlice(b *testing.B) {
	data := make([]int, 0)
	for i := 0; i < b.N; i++ {
		data = Insert(data, i, i)
	}
}

func BenchmarkInsertSlice2(b *testing.B) {
	data := make([]int, 0)
	for i := 0; i < b.N; i++ {
		data = Insert2(data, i, i)
	}
}
```

Running a benchmark of this seems way off from how I would expect an insert to look.

```
goos: linux
goarch: amd64
pkg: slices
cpu: AMD Ryzen 9 7900X 12-Core Processor
BenchmarkInsertSlice-24           153384            112324 ns/op
BenchmarkInsertSlice2-24        189345357                6.104 ns/op
```

**Comment by wenlingang** [comment]
> On second glance, something seems off
> 
> ```
> package slices
> 
> import (
> 	"testing"
> )
> 
> // Insert inserts an element at index i.
> // Play: https://go.dev/play/p/Eu3pk6_ODVQ
> func Insert[T any](collection []T, i int, element T) []T {
> 	result := make([]T, len(collection)+1)
> 	copy(result, collection[:i])
> 	result[i] = element
> 	copy(result[i+1:], collection[i:])
> 
> 	return result
> }
> 
> // Insert inserts an element at index i.
> func Insert2[T any](collection []T, i int, element T) []T {
> 	return append(collection[:i], append([]T{element}, collection[i:]...)...)
> }
> 
> func BenchmarkInsertSlice(b *testing.B) {
> 	data := make([]int, 0)
> 	for i := 0; i < b.N; i++ {
> 		data = Insert(data, i, i)
> 	}
> }
> 
> func BenchmarkInsertSlice2(b *testing.B) {
> 	data := make([]int, 0)
> 	for i := 0; i < b.N; i++ {
> 		data = Insert2(data, i, i)
> 	}
> }
> ```
> 
> Running a benchmark of this seems way off from how I would expect an insert to look.
> 
> ```
> goos: linux
> goarch: amd64
> pkg: slices
> cpu: AMD Ryzen 9 7900X 12-Core Processor
> BenchmarkInsertSlice-24           153384            112324 ns/op
> BenchmarkInsertSlice2-24        189345357                6.104 ns/op
> ```

Thank you. After testing, it is indeed as you said, and I modified it again

**Comment by samber** [comment]
Wow, the difference between both versions is impressive!

Sorry for the delay.

I like your helper, but I'm not sure calling it `Insert` is self-explanatory.

JS, PHP, C++ and Rust named it "splice".

**Comment by samber** [comment]
And I think we should leverage vaargs to write a single helper instead of 2.

**Comment by wenlingang** [comment]
@samber Thank you for your suggestion. I found that it can be further optimized, and I have already done it. Additionally, the name 'Insert' is borrowed from Ruby's Array#insert, though 'Splice' is also a good name.

**Review by samber — CHANGES_REQUESTED** [review]

**Comment by samber** [comment]
I made some changes:
- handle overflow
- negative index
- insert into newly allocated slice instead of `append()`

**Pull request merged**
